#!/bin/bash

# Frontend-User Testing Checklist
# This script provides instructions for testing the frontend-user application

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Frontend-User API Integration - Testing Guide            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ Step 1: Verify Frontend Server is Running"
echo "   - Frontend should be running on: http://localhost:5173"
echo "   - Terminal shows: VITE ready in XXX ms"
echo ""

echo "🚀 Step 2: Start Backend Server (Required)"
echo "   Run in a new terminal:"
echo "   $ cd backend"
echo "   $ ./mvnw spring-boot:run"
echo ""
echo "   Or with Maven:"
echo "   $ mvn clean install"
echo "   $ mvn spring-boot:run"
echo ""

echo "📋 Step 3: Check Environment Variables"
echo "   Backend requires these environment variables (for dev profile):"
echo "   - DB_URL: Database URL"
echo "   - DB_USERNAME: Database user"
echo "   - DB_PASSWORD: Database password"
echo "   - JWT_SECRET: JWT signing secret"
echo "   - MAIL_USERNAME: Gmail username"
echo "   - MAIL_PASSWORD: Gmail app password"
echo "   - VNPAY_TMN_CODE: VNPay merchant code"
echo "   - VNPAY_HASH_SECRET: VNPay hash secret"
echo ""

echo "🧪 Step 4: Test API Endpoints"
echo ""
echo "   4.1 Test Registration:"
echo "       POST http://localhost:5173/register"
echo "       - Fill form with:"
echo "         Name: Test User"
echo "         Email: test@example.com"
echo "         Password: TestPassword123!@#"
echo "       - Expected: Submit to http://localhost:8080/api/auth/register"
echo "       - Result: Redirect to login or show error"
echo ""

echo "   4.2 Test Login:"
echo "       POST http://localhost:5173/login"
echo "       - Use: test@example.com / TestPassword123!@#"
echo "       - Expected: JWT token stored in localStorage"
echo "       - Result: Redirect to home page"
echo ""

echo "   4.3 Test Menu Loading:"
echo "       GET http://localhost:5173/menu"
echo "       - Expected: Load from http://localhost:8080/api/menu"
echo "       - Result: Display menu items with categories"
echo ""

echo "   4.4 Test Booking:"
echo "       POST http://localhost:5173/booking"
echo "       - Fill form and submit"
echo "       - Expected: Submit to http://localhost:8080/api/reservation"
echo "       - Result: Success/error message displayed"
echo ""

echo "🔧 Step 5: Debug in Browser"
echo "   1. Open Browser DevTools (F12)"
echo "   2. Go to Network tab"
echo "   3. Filter by API calls (search '/api')"
echo "   4. Check request/response bodies"
echo "   5. Look for status codes and error messages"
echo ""

echo "💾 Step 6: Check Local Storage"
echo "   In browser console:"
echo "   - localStorage.getItem('authToken')"
echo "   - localStorage.getItem('user')"
echo ""

echo "❌ Troubleshooting"
echo ""
echo "   If backend is not accessible:"
echo "   1. Ensure backend is running on port 8080"
echo "   2. Check http://localhost:8080 in browser"
echo "   3. Check backend startup logs for errors"
echo ""

echo "   If registration/login fails:"
echo "   1. Check browser console for error messages"
echo "   2. Verify backend /api/auth/register and /api/auth/login endpoints"
echo "   3. Check database connection"
echo "   4. Verify JWT_SECRET environment variable is set"
echo ""

echo "   If menu doesn't load:"
echo "   1. Check if logged in (some APIs may require auth)"
echo "   2. Verify /api/menu endpoint is working"
echo "   3. Use curl: curl http://localhost:8080/api/menu"
echo ""

echo "📚 Additional Resources"
echo "   - API Documentation: /docs/api-spec.yaml"
echo "   - Frontend Guide: /frontend-user/API_INTEGRATION.md"
echo "   - Full Summary: /FRONTEND_INTEGRATION_SUMMARY.md"
echo ""

echo "✨ Current Status"
echo "   ✅ Frontend code complete"
echo "   ✅ All TypeScript errors fixed"
echo "   ✅ API services integrated"
echo "   ✅ Development server running"
echo "   ⏳ Awaiting backend startup"
echo ""

echo "🎯 Next Steps"
echo "   1. Start backend server"
echo "   2. Test registration on http://localhost:5173/register"
echo "   3. Test login on http://localhost:5173/login"
echo "   4. Test menu on http://localhost:5173/menu"
echo "   5. Test booking on http://localhost:5173/booking"
echo ""
