# ================================================
# DEV Profile
# ================================================
spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# === JWT ===
jwt:
  secret: 
  expiration: 86400000 # 24h
  refresh-expiration: 604800000 # 7 days

# === EMAIL (Gmail SMTP - DEV) ===
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: 23521431@gm.uit.edu.vn
  password: ziohnvcahldxjuqn
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        starttls.required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

# === VNPay (SANDBOX) ===
vnpay:
  version: 2.1.0
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  base-url: https://sandbox.vnpayment.vn
  return-url: http://localhost:5173/payment/vnpay/return

# === MoMo (SANDBOX) ===
momo:
  endpoint: https://test-payment.momo.vn
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  return-url: http://localhost:5173/payment/momo/return

# === ZaloPay (SANDBOX) ===
zalopay:
  app-id: ${ZALOPAY_APP_ID}
  key1: ${ZALOPAY_KEY1}
  key2: ${ZALOPAY_KEY2}
  endpoint: https://sb-openapi.zalopay.vn
  callback-url: http://localhost:5173/payment/zalopay/callback

# === Server ===
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.restaurant: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
